print("Tabela Verdade AND")
print(True and True and True)
print(True and False and True)
print(False and True)
print(False and False)

print("Tabela Verdade XOR")
print(True != True)
print(True != False)
print(False != True)
print(False != False)

print("Tabela Verdade OR")
print(True or True)
print(True or False)
print(False or True)
print(False or False)

print("Tabela Verdade NOT")
print(not True)
print(not False)
